# Define the exports for the prx
PSP_BEGIN_EXPORTS

# These four lines are mandatory (although you can add other functions like module_stop)
# syslib is a psynonym for the single mandatory export.
PSP_EXPORT_START(syslib, 0, 0x8000)
PSP_EXPORT_FUNC(module_start)
PSP_EXPORT_FUNC(module_stop)
PSP_EXPORT_VAR(module_info)
PSP_EXPORT_END

PSP_EXPORT_START (test, 0, 0x4001)
PSP_EXPORT_FUNC_HASH (cfg_branches)
PSP_EXPORT_FUNC_HASH (cfg_branches_likely)
PSP_EXPORT_FUNC_HASH (cfg_branches_noswap)
PSP_EXPORT_FUNC_HASH (cfg_branches_never)
PSP_EXPORT_FUNC_HASH (cfg_branches_always)
PSP_EXPORT_FUNC_HASH (cfg_branchlink)
PSP_EXPORT_FUNC_HASH (cfg_jumptobegin)
PSP_EXPORT_FUNC_HASH (cfg_strangerefs)
PSP_EXPORT_FUNC_HASH (cfg_callnoswap)
PSP_EXPORT_FUNC_HASH (cfg_switch)
PSP_EXPORT_FUNC_HASH (graph_double_break)
PSP_EXPORT_FUNC_HASH (graph_nested_ifs)
PSP_EXPORT_FUNC_HASH (graph_for_inside_if)
PSP_EXPORT_END


PSP_END_EXPORTS
